language: c

sudo: required

env:
  - global:
      - WARNINGS_ARE_ERRORS=1
      - REMAKE_TEST_INSTALL_PACKAGES=true

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget libv8-dev
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package richfitz/storr
  - ./travis-tool.sh github_package jimhester/covr

script: ./travis-tool.sh run_tests

after_success:
  - Rscript -e 'library(covr); coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
  slack: bdkd:hY2eBCaH3bbsvNwlWwOfFdfr
