init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

build_script:
  - travis-tool.sh install_deps
  - ./travis-tool.sh github_package richfitz/rainbowrite

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs
